### ISSUE TITLE
Feature request: State the differences with uutils-coreutils in README

### ISSUE THREAD

**Issue by PedroHLC** [ras-drive/r-utils#5]
**Is your feature request related to a problem? Please describe.**
Curious what are the development differences between this and widely available https://github.com/uutils/coreutils (besides the license)

**Describe the solution you'd like**
Add it to the README for others interested.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ras-drive** [comment]
I didn't even think about adding this to the README, I obviously chose the GPL over the MIT license because I believe that utilities like these should be free for all user and I'd rather if my work is used in any way it isn't commercial. I'm really doing this mostly as a learning exercise to become more comfortable with writing Rust code and I also found Linux as my real foray into learning about coding so it has a special spot in my heart, system tooling like the GNU Utils seemed like an obvious choice. I will definitely be updating the README soon and thank you for the input!
